<#
.SYNOPSIS
  Podcast-in-a-Box — record, transcribe, clean, clone your voice, generate show notes.
  Flow: Raw recording → Whisper transcribe → pedalboard denoise → XTTSv2 clone (optional)
        → Ollama writes show notes → ffmpeg final render
#>

param(
  [Parameter(Mandatory=$true)][string]$InputAudio,
  [string]$OutputDir = "$env:USERPROFILE\Podcasts",
  [string]$ShowName = "My Episode",
  [switch]$CloneVoice,
  [string]$VoiceSample = "",
  [switch]$AddIntroOutro
)

$ErrorActionPreference = "Stop"
$StartTime = Get-Date
$WorkDir = Join-Path $env:TEMP "podcast_$([System.IO.Path]::GetRandomFileName())"
$null = New-Item -ItemType Directory -Path $WorkDir -Force, $OutputDir -Force

function Step { Write-Host "`n▌ $_" -ForegroundColor Cyan }
function Ok  { Write-Host "  ✓ $_" -ForegroundColor Green }
function Warn{ Write-Host "  ⚠ $_" -ForegroundColor Yellow }

Write-Host @"

  ╔═══════════════════════════════════════╗
  ║     Podcast-in-a-Box Pipeline v1.0   ║
  ║  $InputAudio
  ╚═══════════════════════════════════════╝
"@ -ForegroundColor Magenta

# 1. TRANSCRIBE with Whisper
Step "1/5 Transcription — Whisper large-v3"
$transcriptDir = Join-Path $WorkDir "transcript"
$null = New-Item -ItemType Directory -Path $transcriptDir -Force

whisper $InputAudio --model large-v3 --output_dir $transcriptDir --output_format txt,srt,json --language en 2>&1 | Out-Null
$txtFile = Get-ChildItem $transcriptDir -Filter "*.txt" | Select-Object -First 1
if ($txtFile) {
  Ok "Transcription complete"
  $transcript = Get-Content $txtFile.FullName -Raw
} else {
  Warn "Transcription failed — continuing with placeholder"
  $transcript = "[Transcription unavailable]"
}

# 2. AUDIO CLEANUP with pedalboard
Step "2/5 Audio Cleanup — Pedalboard"
$cleanFile = Join-Path $WorkDir "clean.wav"
python -c @"
from pedalboard import Pedalboard, NoiseGate, Compressor, LowpassFilter, HighpassFilter
from pedalboard.io import AudioFile
with AudioFile(r'$InputAudio'.replace('\\','/')) as f:
  audio = f.read(f.frames)
  sr = f.samplerate
board = Pedalboard([
  HighpassFilter(cutoff_frequency_hz=80),
  NoiseGate(threshold_db=-40, ratio=10),
  Compressor(threshold_db=-20, ratio=4),
  LowpassFilter(cutoff_frequency_hz=16000)
])
effected = board(audio, sr)
with AudioFile(r'$cleanFile'.replace('\\','/'), 'w', sr, effected.shape[0]) as f:
  f.write(effected)
print("Cleanup done")
"@ 2>&1 | Out-Null
if (Test-Path $cleanFile) { Ok "Audio cleaned (gate + comp + EQ)" } else { Warn "Cleanup failed"; Copy-Item $InputAudio $cleanFile }

# 3. VOICE CLONE with XTTSv2 (optional)
Step "3/5 Voice Processing"
$finalVocals = $cleanFile
if ($CloneVoice -and $VoiceSample -and (Test-Path $VoiceSample)) {
  $clonedFile = Join-Path $WorkDir "cloned.wav"
  # XTTSv2 API call would go here
  Warn "Voice cloning requires XTTSv2 API running on port 8020"
  Warn "Skipping clone — using cleaned audio"
} else {
  Ok "Using original voice (cleaned)"
}

# 4. SHOW NOTES with Ollama
Step "4/5 Show Notes — Ollama"
$notesFile = Join-Path $WorkDir "show_notes.md"
$ollama = Get-Command ollama -ErrorAction SilentlyContinue
if ($ollama -and $transcript) {
  $notesPrompt = @"
From this transcript, generate:
1. Episode title (catchy, 6 words max)
2. 3 key takeaways (bullet points)
3. Timestamped highlights (3 most interesting moments with their timestamps)
4. 3 SEO tags

Transcript:
$transcript
"@
  $notes = & ollama run llama3.1:8b $notesPrompt 2>$null
  if ($notes) {
    $notes | Out-File -FilePath $notesFile -Encoding UTF8
    Ok "Show notes generated"
  }
}
if (-not (Test-Path $notesFile)) {
  "# $ShowName`n`nGenerated by Podcast-in-a-Box" | Out-File -FilePath $notesFile -Encoding UTF8
}

# 5. FINAL RENDER with optional intro/outro
Step "5/5 Final Render — ffmpeg"
$finalFile = Join-Path $OutputDir "$ShowName-episode.wav"

if ($AddIntroOutro) {
  $intro = Join-Path $PSScriptRoot "assets\intro.wav"
  $outro = Join-Path $PSScriptRoot "assets\outro.wav"
  if (Test-Path $intro -and Test-Path $outro) {
    $introPart = Join-Path $WorkDir "intro_combined.wav"
    sox $intro $finalVocals $outro $introPart 2>&1 | Out-Null
    Copy-Item $introPart $finalFile
  } else {
    Copy-Item $finalVocals $finalFile
    Warn "Intro/outro assets not found — add them to installers\automations\assets\"
  }
} else {
  Copy-Item $finalVocals $finalFile
}

$elapsed = [math]::Round(((Get-Date) - $StartTime).TotalSeconds, 0)
$size = [math]::Round((Get-Item $finalFile).Length / 1MB, 1)
Ok "Podcast complete in ${elapsed}s (${size}MB)"

Write-Host @"

  ═══════════════════════════════════════
  ✓ OUTPUT: $finalFile
  ✓ TRANSCRIPT: $(Get-ChildItem $transcriptDir -Filter "*.txt" | Select-Object -First 1).Name
  ✓ SHOW NOTES: $(Split-Path $notesFile -Leaf)
  ═══════════════════════════════════════

  🎙️ Pro Podcast Pack ($5 — one-time):
  • Multi-speaker diarization (labels each speaker)
  • Automatic silence removal (tightens rambling)
  • YouTube+Spotify metadata template
  • Intro/outro music generator (AceStep-powered)
  • Batch process an entire season (10+ episodes)

  → https://gumroad.com/l/podcast-automation-pro

  📋 Need a podcast microphone?
  → https://amzn.to/3XzJkR7

"@ -ForegroundColor DarkGray

Remove-Item $WorkDir -Recurse -Force -ErrorAction SilentlyContinue
