import type { SeparationModel } from './model-catalog';

export const EXTENDED_ENGINE_META = {
  ensemble: {
    label: 'Ensemble',
    subtitle: 'Multi-model fusion presets — vocal_balanced, karaoke, etc.',
    color: '#e879f9',
    glow: 'rgba(232,121,249,0.4)',
  },
  karaoke: {
    label: 'Karaoke',
    subtitle: 'Lead vs backing vocal separation',
    color: '#fda4af',
    glow: 'rgba(253,164,175,0.4)',
  },
  postfx: {
    label: 'Post-FX',
    subtitle: 'Apollo restoration · Matchering · Transkun MIDI',
    color: '#34d399',
    glow: 'rgba(52,211,153,0.35)',
  },
  instrument: {
    label: 'Instruments',
    subtitle: 'Per-instrument extractors — guitar, piano, strings…',
    color: '#a3e635',
    glow: 'rgba(163,230,53,0.35)',
  },
} as const;

export const EXTENDED_DEFAULT_MODELS = {
  ensemble: 'ensemble_vocal_balanced',
  karaoke: 'karaoke_mvsep_team',
  postfx: 'postfx_apollo_vocal',
  instrument: 'inst_guitar_sw',
} as const;

export const EXTENDED_MODELS: SeparationModel[] = [
  // ── SOTA Roformer / SCNet ─────────────────────────────────
  {
    id: 'roformer_bs_368',
    engine: 'roformer',
    category: 'vocal',
    name: 'BS-Roformer ep368',
    tagline: '2025 SOTA vocal (SDR 12.9)',
    filename: 'model_bs_roformer_ep_368_sdr_12.9628.ckpt',
    description: 'Latest viperx BS-Roformer checkpoint. Tied #1 on audio-separator vocal leaderboard. Auto-downloads on first use.',
    stems: [2],
    tier: 'S',
    accent: '#f472b6',
    glow: 'rgba(244,114,182,0.5)',
    glyph: '◉',
    tags: ['sota', '2025', 'vocal'],
    recommendedFor: ['acapellas', 'critical vocal work'],
    speed: 'slow',
    quality: 97,
  },
  {
    id: 'roformer_polarformer',
    engine: 'roformer',
    category: 'vocal',
    name: 'BS PolarFormer',
    tagline: '2026 polar-coordinate transformer',
    filename: 'model_bs_polarformer_float16.ckpt',
    description: 'New PolarFormer architecture with long-context polar embeddings. SDR 11.76 vocals on MVSEP multisong — flagship 2026 model class.',
    stems: [2],
    tier: 'S',
    accent: '#c026d3',
    glow: 'rgba(192,38,211,0.45)',
    glyph: '◎',
    tags: ['2026', 'polarformer', 'sota'],
    recommendedFor: ['masters', 'long-form tracks'],
    speed: 'slow',
    quality: 96,
  },
  {
    id: 'roformer_melband_unwa',
    engine: 'roformer',
    category: 'vocal',
    name: 'MelBand unwa FT',
    tagline: 'Fullness-tuned MelBand',
    filename: 'mel_band_roformer_kim_ft_unwa.ckpt',
    description: 'unwa fine-tune of Kim MelBand Roformer. Tunable fullness profile for vocal-heavy extraction.',
    stems: [2],
    tier: 'A',
    accent: '#ec4899',
    glow: 'rgba(236,72,153,0.4)',
    glyph: '❋',
    tags: ['melband', 'unwa'],
    recommendedFor: ['vocal-heavy mixes'],
    speed: 'slow',
    quality: 93,
  },
  {
    id: 'roformer_melband_big_beta4',
    engine: 'roformer',
    category: 'vocal',
    name: 'MelBand Big Beta 4',
    tagline: 'unwa beta — max vocal capture',
    filename: 'melband_roformer_big_beta4.ckpt',
    description: 'Large beta MelBand checkpoint optimized for maximum vocal fullness. May trade some cleanliness for presence.',
    stems: [2],
    tier: 'A',
    accent: '#db2777',
    glow: 'rgba(219,39,119,0.4)',
    glyph: '✺',
    tags: ['melband', 'fullness'],
    recommendedFor: ['quiet vocals', 'buried leads'],
    speed: 'slow',
    quality: 91,
  },
  {
    id: 'roformer_hyperace_v2_vocals',
    engine: 'roformer',
    category: 'vocal',
    name: 'HyperACE v2 Vocals',
    tagline: 'unwa — vocal fullness profile',
    description: 'BS-Roformer HyperACE v2 tuned for maximum vocal bleedless score (SDR 11.39). MVSEP March 2026 addition.',
    stems: [2],
    tier: 'S',
    accent: '#f9a8d4',
    glow: 'rgba(249,168,212,0.45)',
    glyph: '△',
    tags: ['hyperace', 'vocals'],
    recommendedFor: ['dense mixes', 'EDM vocals'],
    speed: 'slow',
    quality: 94,
  },
  {
    id: 'roformer_hyperace_v2_instrum',
    engine: 'roformer',
    category: 'instrumental',
    name: 'HyperACE v2 Instrum',
    tagline: 'unwa — instrumental fullness profile',
    description: 'HyperACE v2 instrumental profile (SDR 17.40). Maximizes backing track presence and stereo width.',
    stems: [2],
    tier: 'A',
    accent: '#818cf8',
    glow: 'rgba(129,140,248,0.4)',
    glyph: '▽',
    tags: ['hyperace', 'instrumental'],
    recommendedFor: ['minus-one', 'instrumentals'],
    speed: 'slow',
    quality: 92,
  },
  {
    id: 'roformer_dereverb_anvuew',
    engine: 'roformer',
    category: 'restoration',
    name: 'DeReverb anvuew',
    tagline: 'BS-Roformer room removal',
    filename: 'dereverb_mel_band_roformer_anvuew_sdr_19.1729.ckpt',
    description: 'anvuew MelBand de-reverb model. Newer mono vocal room removal than FoxJoy Reverb HQ — processes stereo channels independently.',
    stems: [2],
    tier: 'A',
    accent: '#5eead4',
    glow: 'rgba(94,234,212,0.35)',
    glyph: '≋',
    tags: ['dereverb', 'room'],
    recommendedFor: ['podcasts', 'roomy vocals'],
    speed: 'balanced',
    quality: 88,
  },
  {
    id: 'roformer_bs_sw_6s',
    engine: 'roformer',
    category: 'multistem',
    name: 'BS-Roformer SW 6-Stem',
    tagline: 'vocals · bass · drums · guitar · piano · other',
    description: 'MVSEP BS-Roformer SW outputs 6 stems in one pass. Replaces Demucs 6s for many tracks with superior guitar/piano SDR.',
    stems: [6],
    tier: 'S',
    accent: '#e879f9',
    glow: 'rgba(232,121,249,0.45)',
    glyph: '⬡',
    tags: ['6-stem', 'multistem'],
    recommendedFor: ['band mixes', 'sampling'],
    speed: 'slow',
    quality: 94,
  },
  {
    id: 'scnet_xl_ihf',
    engine: 'roformer',
    category: 'vocal',
    name: 'SCNet XL IHF',
    tagline: 'MVSEP 2025 ensemble core',
    filename: 'model_scnet_ep_36_sdr_10.0891.ckpt',
    description: 'SCNet XL IHF — core of MVSEP Ensemble 2025.06. Competitive with Roformer, sometimes better on edge cases.',
    stems: [2],
    tier: 'S',
    accent: '#a78bfa',
    glow: 'rgba(167,139,250,0.45)',
    glyph: '◈',
    tags: ['scnet', 'ensemble'],
    recommendedFor: ['vocals', 'ensembles'],
    speed: 'slow',
    quality: 93,
  },
  {
    id: 'scnet_xl',
    engine: 'roformer',
    category: 'vocal',
    name: 'SCNet XL',
    tagline: 'Sparse compression net',
    filename: 'model_scnet_ep_54_sdr_9.8051.ckpt',
    description: 'Full SCNet XL checkpoint. Transformer-sparse architecture with near-Roformer quality at different failure modes.',
    stems: [2],
    tier: 'A',
    accent: '#8b5cf6',
    glow: 'rgba(139,92,246,0.4)',
    glyph: '◇',
    tags: ['scnet'],
    recommendedFor: ['general vocal split'],
    speed: 'slow',
    quality: 90,
  },

  // ── Demucs specialty ──────────────────────────────────────
  {
    id: 'demucs_vocals_2023',
    engine: 'demucs',
    category: 'vocal',
    name: 'Demucs4 Vocals 2023',
    tagline: 'Vocal-fine-tuned Demucs4 HT',
    filename: 'model_vocals_htdemucs_sdr_8.78.ckpt',
    description: 'Demucs4 HT fine-tuned on vocal/instrumental data. Different failure profile from MDX — excellent in ensembles.',
    stems: [2],
    tier: 'A',
    accent: '#22d3ee',
    glow: 'rgba(34,211,238,0.4)',
    glyph: '♪',
    tags: ['demucs', 'vocal', 'ensemble'],
    recommendedFor: ['ensemble fusion', 'vocal isolation'],
    speed: 'balanced',
    quality: 86,
  },

  // ── MDX upgrades ──────────────────────────────────────────
  {
    id: 'mdx_inst_hq_4',
    engine: 'mdx',
    category: 'instrumental',
    name: 'Inst HQ v4',
    tagline: 'UVR MDX instrumental v4',
    filename: 'UVR-MDX-NET-Inst_HQ_4.onnx',
    description: 'Fourth-gen MDX instrumental model. Improved backing track clarity over v1/v3.',
    stems: [2],
    tier: 'A',
    accent: '#6366f1',
    glow: 'rgba(99,102,241,0.4)',
    glyph: '◆',
    tags: ['instrumental'],
    recommendedFor: ['backing tracks'],
    speed: 'balanced',
    quality: 88,
  },
  {
    id: 'mdx_inst_hq_5',
    engine: 'mdx',
    category: 'instrumental',
    name: 'Inst HQ v5',
    tagline: 'Latest MDX instrumental',
    filename: 'UVR-MDX-NET-Inst_HQ_5.onnx',
    description: 'Newest UVR MDX instrumental HQ checkpoint. Best MDX-B instrumental SDR on MVSEP benchmarks.',
    stems: [2],
    tier: 'A',
    accent: '#4f46e5',
    glow: 'rgba(79,70,229,0.4)',
    glyph: '◆',
    tags: ['instrumental', 'latest'],
    recommendedFor: ['karaoke prep', 'live backing'],
    speed: 'balanced',
    quality: 89,
  },
  {
    id: 'mdx23c_8k_v2',
    engine: 'mdx',
    category: 'ensemble',
    name: 'MDX23C 8K v2',
    tagline: 'Higher-res MDX23C checkpoint',
    filename: 'model_mdx23c_ep_168_sdr_7.0207.ckpt',
    description: 'MDX23C 8K FFT v2 with improved multisong metrics over v1. Full-band, no high-frequency cut.',
    stems: [2],
    tier: 'A',
    accent: '#c084fc',
    glow: 'rgba(192,132,252,0.4)',
    glyph: '✧',
    tags: ['mdx23c', '8k'],
    recommendedFor: ['complex mixes'],
    speed: 'slow',
    quality: 90,
  },
  {
    id: 'mdx_crowd_roformer_2025',
    engine: 'mdx',
    category: 'specialty',
    name: 'Crowd Removal Pro',
    tagline: 'Remove crowd & audience noise',
    filename: 'mel_band_roformer_crowd_aufr33_viperx_sdr_8.7144.ckpt',
    description: '2025 crowd/audience model on Roformer architecture. Beats legacy MDX Crowd HQ (SDR 6.27 → 7.21).',
    stems: [2],
    tier: 'A',
    accent: '#a3e635',
    glow: 'rgba(163,230,53,0.35)',
    glyph: '▣',
    tags: ['crowd', '2025'],
    recommendedFor: ['live recordings', 'broadcast'],
    speed: 'balanced',
    quality: 86,
  },

  // ── Ensemble presets ────────────────────────────────────
  {
    id: 'ensemble_vocal_balanced',
    engine: 'ensemble',
    category: 'ensemble',
    name: 'Vocal Balanced',
    tagline: 'audio-separator preset — best overall',
    description: 'Fuses 2 top models with avg_fft weighting. Community-tested best overall vocal quality without manual model picking.',
    stems: [2],
    tier: 'S',
    accent: '#e879f9',
    glow: 'rgba(232,121,249,0.45)',
    glyph: '✦',
    tags: ['preset', 'fusion'],
    recommendedFor: ['default vocal work', 'unknown genre'],
    speed: 'slow',
    quality: 95,
  },
  {
    id: 'ensemble_vocal_clean',
    engine: 'ensemble',
    category: 'ensemble',
    name: 'Vocal Clean',
    tagline: 'Minimal instrumental bleed',
    description: 'Ensemble preset optimized for cleanest vocals with min_fft fusion. Trades some vocal fullness for bleedless output.',
    stems: [2],
    tier: 'S',
    accent: '#d8b4fe',
    glow: 'rgba(216,180,254,0.4)',
    glyph: '○',
    tags: ['preset', 'clean'],
    recommendedFor: ['acapellas', 'remix stems'],
    speed: 'slow',
    quality: 94,
  },
  {
    id: 'ensemble_vocal_full',
    engine: 'ensemble',
    category: 'ensemble',
    name: 'Vocal Full',
    tagline: 'Maximum vocal capture',
    description: 'max_fft ensemble — captures every vocal nuance including breath and ad-libs. May include slight instrumental bleed.',
    stems: [2],
    tier: 'A',
    accent: '#f0abfc',
    glow: 'rgba(240,171,252,0.4)',
    glyph: '●',
    tags: ['preset', 'fullness'],
    recommendedFor: ['quiet vocals', 'layered harmonies'],
    speed: 'slow',
    quality: 92,
  },
  {
    id: 'ensemble_vocal_rvc',
    engine: 'ensemble',
    category: 'ensemble',
    name: 'Vocal RVC',
    tagline: 'Optimized for AI voice training',
    description: 'avg_wave fusion tuned for RVC/AI voice clone datasets. Clean, consistent vocal stems for model training.',
    stems: [2],
    tier: 'A',
    accent: '#c084fc',
    glow: 'rgba(192,132,252,0.4)',
    glyph: '◎',
    tags: ['preset', 'rvc', 'ai'],
    recommendedFor: ['RVC datasets', 'voice cloning'],
    speed: 'slow',
    quality: 91,
  },
  {
    id: 'ensemble_karaoke',
    engine: 'ensemble',
    category: 'karaoke',
    name: 'Karaoke Ensemble',
    tagline: '3-model karaoke fusion',
    description: 'audio-separator karaoke preset — fuses 3 models with avg_wave for lead vocal removal while keeping harmonies.',
    stems: [2],
    tier: 'A',
    accent: '#fda4af',
    glow: 'rgba(253,164,175,0.4)',
    glyph: '☆',
    tags: ['preset', 'karaoke'],
    recommendedFor: ['karaoke', 'sing-along'],
    speed: 'slow',
    quality: 88,
  },
  {
    id: 'ensemble_instrumental_clean',
    engine: 'ensemble',
    category: 'instrumental',
    name: 'Instrumental Clean',
    tagline: 'Cleanest minus-one tracks',
    description: 'uvr_max_spec fusion for minimum vocal bleed in instrumental output. Best for live performance backing.',
    stems: [2],
    tier: 'A',
    accent: '#818cf8',
    glow: 'rgba(129,140,248,0.4)',
    glyph: '◇',
    tags: ['preset', 'instrumental'],
    recommendedFor: ['live backing', 'sync'],
    speed: 'slow',
    quality: 90,
  },

  // ── Karaoke lead/back ───────────────────────────────────
  {
    id: 'karaoke_mvsep_team',
    engine: 'karaoke',
    category: 'karaoke',
    name: 'MVSep Karaoke Team',
    tagline: 'Lead · back · instrumental (SDR 10.41)',
    description: 'MVSEP Team BS-Roformer karaoke model. Returns three stems: lead vocals, backing vocals, and instrumental. Best for duets and choir tracks.',
    stems: [3],
    tier: 'S',
    accent: '#fb7185',
    glow: 'rgba(251,113,133,0.45)',
    glyph: '♬',
    tags: ['lead', 'back', '3-stem'],
    recommendedFor: ['duets', 'choir', 'gospel'],
    speed: 'slow',
    quality: 94,
  },
  {
    id: 'karaoke_bs_roformer',
    engine: 'karaoke',
    category: 'karaoke',
    name: 'MDX Karaoke v2',
    tagline: 'Lead vocal removal',
    filename: 'UVR_MDXNET_KARA_2.onnx',
    description: 'High-quality lead vocal karaoke split via MDX Karaoke v2 ONNX. Fallback when 3-stem lead/back is not needed.',
    stems: [2],
    tier: 'A',
    accent: '#f9a8d4',
    glow: 'rgba(249,168,212,0.4)',
    glyph: '♫',
    tags: ['karaoke'],
    recommendedFor: ['covers', 'sing-along'],
    speed: 'balanced',
    quality: 87,
  },

  // ── Drumsep 6/7 ─────────────────────────────────────────
  {
    id: 'drumsep_mdx23c_6',
    engine: 'drumsep',
    category: 'drums',
    name: 'Drumsep MDX23C 6-Stem',
    tagline: 'kick · snare · toms · hh · ride · crash',
    filename: 'MDX23C-DrumSep-aufr33-jarredou.ckpt',
    description: 'jarredou/aufr33 MDX23C drum separator. Splits drums into 6 micro-stems including separate hi-hat, ride, and crash. MVSEP 7-stem drumsep core.',
    stems: [6, 7],
    tier: 'S',
    accent: '#fbbf24',
    glow: 'rgba(251,191,36,0.5)',
    glyph: '⊛',
    tags: ['drums', '7-stem', 'mdx23c'],
    recommendedFor: ['drum sampling', 'breakdown', 'EDM'],
    speed: 'slow',
    quality: 92,
  },
  {
    id: 'drumsep_mdx23c_5',
    engine: 'drumsep',
    category: 'drums',
    name: 'Drumsep MDX23C 5-Stem',
    tagline: 'kick · snare · toms · hh · cymbals',
    filename: 'drumsep_5stems_mdx23c_jarredou.ckpt',
    description: 'jarredou 5-stem MDX23C drum model. Higher per-stem SDR than 4-stem Demucs drumsep on kick and snare.',
    stems: [5],
    tier: 'A',
    accent: '#f59e0b',
    glow: 'rgba(245,158,11,0.4)',
    glyph: '⊕',
    tags: ['drums', '5-stem'],
    recommendedFor: ['drum loops', 'hip-hop'],
    speed: 'slow',
    quality: 88,
  },

  // ── Post-FX ─────────────────────────────────────────────
  {
    id: 'postfx_apollo_vocal',
    engine: 'postfx',
    category: 'restoration',
    name: 'Apollo Vocal Restore',
    tagline: 'JusperLee super-resolution',
    description: 'Apollo LQ MP3 restoration on vocal stem. Reconstructs high-frequency detail lost in lossy codecs. Runs after separation.',
    stems: [2],
    tier: 'A',
    accent: '#34d399',
    glow: 'rgba(52,211,153,0.4)',
    glyph: '↑',
    tags: ['apollo', 'restore', 'vocals'],
    recommendedFor: ['mp3 sources', 'noisy vocals'],
    speed: 'balanced',
    quality: 85,
  },
  {
    id: 'postfx_apollo_universal',
    engine: 'postfx',
    category: 'restoration',
    name: 'Apollo Universal',
    tagline: 'Restore all stems',
    description: 'Apollo enhancement applied to every output stem. Useful for archival material and low-bitrate sources.',
    stems: [2, 4, 6],
    tier: 'B',
    accent: '#6ee7b7',
    glow: 'rgba(110,231,183,0.35)',
    glyph: '⇡',
    tags: ['apollo', 'restore'],
    recommendedFor: ['archival', 'remastering'],
    speed: 'slow',
    quality: 82,
  },
  {
    id: 'postfx_matchering',
    engine: 'postfx',
    category: 'restoration',
    name: 'Matchering',
    tagline: 'Reference-match mastering',
    description: 'Matchering masters your output to match a reference track\'s RMS, frequency response, peak, and stereo width. Requires a reference audio file.',
    stems: [2, 4, 6],
    tier: 'specialty',
    accent: '#fcd34d',
    glow: 'rgba(252,211,77,0.35)',
    glyph: '≈',
    tags: ['matchering', 'mastering', 'reference'],
    recommendedFor: ['mastering', 'loudness matching'],
    speed: 'fast',
    quality: 80,
  },
  {
    id: 'postfx_transkun_piano',
    engine: 'postfx',
    category: 'specialty',
    name: 'Transkun Piano MIDI',
    tagline: 'Audio → MIDI transcription',
    description: 'Transkun SOTA piano transcription. Converts piano stem (or mix) to MIDI with note velocity and pedal data. Outputs .mid alongside stems.',
    stems: [2, 4, 6],
    tier: 'specialty',
    accent: '#93c5fd',
    glow: 'rgba(147,197,253,0.35)',
    glyph: '♯',
    tags: ['midi', 'piano', 'transcription'],
    recommendedFor: ['piano covers', 'notation', 'sampling'],
    speed: 'slow',
    quality: 88,
  },

  // ── Instruments — multistem & per-target extractors ─────
  {
    id: 'inst_bs_roformer_sw',
    engine: 'instrument',
    category: 'multistem',
    name: 'BS-Roformer SW 6-Stem',
    tagline: 'vocals · bass · drums · guitar · piano · other',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'MVSEP default 6-stem model (jarredou). Guitar SDR 9.05, piano 7.83 — best single-pass melodic isolation.',
    stems: [6],
    tier: 'S',
    accent: '#e879f9',
    glow: 'rgba(232,121,249,0.45)',
    glyph: '⬡',
    tags: ['6-stem', 'guitar', 'piano'],
    recommendedFor: ['band mixes', 'sampling', 'arrangement'],
    speed: 'slow',
    quality: 94,
  },
  {
    id: 'inst_guitar',
    engine: 'instrument',
    category: 'multistem',
    name: 'Guitar Extractor',
    tagline: 'becruily MelBand — dedicated guitar',
    filename: 'melband_roformer_guitar_becruily.ckpt',
    description: 'MelBand Roformer guitar model by becruily. Run on full mix or after 4-stem.other. Auto-downloads from HuggingFace.',
    stems: [2],
    tier: 'A',
    accent: '#a3e635',
    glow: 'rgba(163,230,53,0.35)',
    glyph: '⚡',
    tags: ['guitar', 'instrument'],
    recommendedFor: ['sampling', 'covers'],
    speed: 'slow',
    quality: 84,
  },
  {
    id: 'inst_guitar_sw',
    engine: 'instrument',
    category: 'multistem',
    name: 'Guitar (BS-Roformer SW)',
    tagline: 'SW guitar stem — SDR 9.05',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Extract guitar stem from BS-Roformer SW checkpoint. Highest guitar SDR on MVSEP leaderboard.',
    stems: [2],
    tier: 'S',
    accent: '#bef264',
    glow: 'rgba(190,242,100,0.35)',
    glyph: '⚡',
    tags: ['guitar', 'instrument'],
    recommendedFor: ['sampling', 'rock', 'pop'],
    speed: 'slow',
    quality: 90,
  },
  {
    id: 'inst_piano',
    engine: 'instrument',
    category: 'multistem',
    name: 'Piano Extractor',
    tagline: 'BS-Roformer SW piano — SDR 7.83',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Extract piano/keys from BS-Roformer SW. Pair with Transkun post-FX for MIDI output.',
    stems: [2],
    tier: 'A',
    accent: '#86efac',
    glow: 'rgba(134,239,172,0.35)',
    glyph: '♯',
    tags: ['piano', 'instrument'],
    recommendedFor: ['notation', 'sampling'],
    speed: 'slow',
    quality: 82,
  },
  {
    id: 'inst_keys',
    engine: 'instrument',
    category: 'multistem',
    name: 'Keys / Synth Pad',
    tagline: 'Piano stem from SW',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Keyboard and pad isolation via BS-Roformer SW piano stem. Good for electronic and orchestral keys.',
    stems: [2],
    tier: 'A',
    accent: '#6ee7b7',
    glow: 'rgba(110,231,183,0.35)',
    glyph: '♯',
    tags: ['keys', 'piano', 'instrument'],
    recommendedFor: ['sampling', 'remix'],
    speed: 'slow',
    quality: 80,
  },
  {
    id: 'inst_bass_sw',
    engine: 'instrument',
    category: 'multistem',
    name: 'Bass (BS-Roformer SW)',
    tagline: 'SW bass stem — SDR 14.6',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Isolate bass from BS-Roformer SW multistem checkpoint.',
    stems: [2],
    tier: 'A',
    accent: '#fcd34d',
    glow: 'rgba(252,211,77,0.35)',
    glyph: '◆',
    tags: ['bass', 'instrument'],
    recommendedFor: ['remix', 'sampling'],
    speed: 'slow',
    quality: 88,
  },
  {
    id: 'inst_drums_sw',
    engine: 'instrument',
    category: 'drums',
    name: 'Drums (BS-Roformer SW)',
    tagline: 'SW drums stem — SDR 14.1',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Full drum kit stem from BS-Roformer SW. For micro-stems use Drumsep tab.',
    stems: [2],
    tier: 'A',
    accent: '#fbbf24',
    glow: 'rgba(251,191,36,0.35)',
    glyph: '◎',
    tags: ['drums', 'instrument'],
    recommendedFor: ['remix', 'sampling'],
    speed: 'slow',
    quality: 87,
  },
  {
    id: 'inst_lead_guitar',
    engine: 'instrument',
    category: 'multistem',
    name: 'Lead Guitar',
    tagline: 'MVSEP lead guitar profile',
    filename: 'melband_roformer_guitar_becruily.ckpt',
    description: 'Lead guitar isolation. Best workflow: 4-stem → guitar stem → re-run lead/rhythm on MVSEP cloud.',
    stems: [2],
    tier: 'A',
    accent: '#f97316',
    glow: 'rgba(249,115,22,0.35)',
    glyph: '⚡',
    tags: ['guitar', 'lead', 'instrument'],
    recommendedFor: ['rock', 'metal'],
    speed: 'slow',
    quality: 78,
  },
  {
    id: 'inst_rhythm_guitar',
    engine: 'instrument',
    category: 'multistem',
    name: 'Rhythm Guitar',
    tagline: 'MVSEP rhythm guitar profile',
    filename: 'melband_roformer_guitar_becruily.ckpt',
    description: 'Rhythm guitar isolation. Run on guitar stem after initial split for cleanest results.',
    stems: [2],
    tier: 'A',
    accent: '#fb923c',
    glow: 'rgba(251,146,60,0.35)',
    glyph: '⚡',
    tags: ['guitar', 'rhythm', 'instrument'],
    recommendedFor: ['rock', 'funk'],
    speed: 'slow',
    quality: 76,
  },
  {
    id: 'inst_electric_guitar',
    engine: 'instrument',
    category: 'multistem',
    name: 'Electric Guitar',
    tagline: 'MVSEP electric profile',
    filename: 'melband_roformer_guitar_becruily.ckpt',
    description: 'Electric guitar extraction tuned for distorted and clean electric tones.',
    stems: [2],
    tier: 'A',
    accent: '#f59e0b',
    glow: 'rgba(245,158,11,0.35)',
    glyph: '⚡',
    tags: ['guitar', 'electric', 'instrument'],
    recommendedFor: ['rock', 'sampling'],
    speed: 'slow',
    quality: 82,
  },
  {
    id: 'inst_acoustic_guitar',
    engine: 'instrument',
    category: 'multistem',
    name: 'Acoustic Guitar',
    tagline: 'MVSEP acoustic profile',
    filename: 'melband_roformer_guitar_becruily.ckpt',
    description: 'Acoustic and fingerstyle guitar isolation from full mix or other stem.',
    stems: [2],
    tier: 'A',
    accent: '#d97706',
    glow: 'rgba(217,119,6,0.35)',
    glyph: '⚡',
    tags: ['guitar', 'acoustic', 'instrument'],
    recommendedFor: ['folk', 'sampling'],
    speed: 'slow',
    quality: 80,
  },
  {
    id: 'inst_woodwinds',
    engine: 'instrument',
    category: 'multistem',
    name: 'Woodwinds',
    tagline: 'UVR HP Wind Inst',
    filename: '17_HP-Wind_Inst-UVR.pth',
    description: 'Classic UVR woodwind extractor. Returns woodwinds + no-woodwinds (other). MVSEP wind SDR 9.82 via cloud.',
    stems: [2],
    tier: 'B',
    accent: '#7dd3fc',
    glow: 'rgba(125,211,252,0.35)',
    glyph: '≋',
    tags: ['woodwind', 'instrument'],
    recommendedFor: ['orchestral', 'film'],
    speed: 'balanced',
    quality: 72,
  },
  {
    id: 'inst_strings',
    engine: 'instrument',
    category: 'multistem',
    name: 'Strings (Orchestral)',
    tagline: 'MVSep strings BS-Roformer',
    filename: '17_HP-Wind_Inst-UVR.pth',
    description: 'Orchestral strings isolation. VR woodwind proxy locally; MVSEP strings BS-Roformer (SDR 5.41) on cloud.',
    stems: [2],
    tier: 'B',
    accent: '#c4b5fd',
    glow: 'rgba(196,181,253,0.35)',
    glyph: '♪',
    tags: ['strings', 'instrument'],
    recommendedFor: ['orchestral', 'film'],
    speed: 'slow',
    quality: 68,
  },
  {
    id: 'inst_violin',
    engine: 'instrument',
    category: 'multistem',
    name: 'Violin',
    tagline: 'MVSEP violin model',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Violin stem extraction. Use other stem as starting point; MVSEP violin BS-Roformer available via cloud reprocess.',
    stems: [2],
    tier: 'B',
    accent: '#ddd6fe',
    glow: 'rgba(221,214,254,0.35)',
    glyph: '♪',
    tags: ['violin', 'strings', 'instrument'],
    recommendedFor: ['classical', 'film'],
    speed: 'slow',
    quality: 65,
  },
  {
    id: 'inst_cello',
    engine: 'instrument',
    category: 'multistem',
    name: 'Cello',
    tagline: 'MVSEP cello profile',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Cello isolation from mix or strings stem. Refine with MVSEP cello model on cloud.',
    stems: [2],
    tier: 'B',
    accent: '#a78bfa',
    glow: 'rgba(167,139,250,0.35)',
    glyph: '♪',
    tags: ['cello', 'strings', 'instrument'],
    recommendedFor: ['classical', 'film'],
    speed: 'slow',
    quality: 64,
  },
  {
    id: 'inst_viola',
    engine: 'instrument',
    category: 'multistem',
    name: 'Viola',
    tagline: 'MVSEP viola profile',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Viola stem extraction for orchestral and chamber arrangements.',
    stems: [2],
    tier: 'B',
    accent: '#8b5cf6',
    glow: 'rgba(139,92,246,0.35)',
    glyph: '♪',
    tags: ['viola', 'strings', 'instrument'],
    recommendedFor: ['classical'],
    speed: 'slow',
    quality: 62,
  },
  {
    id: 'inst_saxophone',
    engine: 'instrument',
    category: 'multistem',
    name: 'Saxophone',
    tagline: 'BS-Roformer sax — SDR 9.77',
    filename: '17_HP-Wind_Inst-UVR.pth',
    description: 'Saxophone isolation. VR wind proxy locally; MVSEP BS-Roformer sax (SDR 9.77) on cloud.',
    stems: [2],
    tier: 'A',
    accent: '#38bdf8',
    glow: 'rgba(56,189,248,0.35)',
    glyph: '♪',
    tags: ['saxophone', 'brass', 'instrument'],
    recommendedFor: ['jazz', 'sampling'],
    speed: 'slow',
    quality: 78,
  },
  {
    id: 'inst_trumpet',
    engine: 'instrument',
    category: 'multistem',
    name: 'Trumpet',
    tagline: 'MVSEP trumpet model',
    filename: '17_HP-Wind_Inst-UVR.pth',
    description: 'Trumpet and brass lead isolation. VR wind proxy; MVSEP trumpet BS-Roformer via cloud.',
    stems: [2],
    tier: 'B',
    accent: '#fbbf24',
    glow: 'rgba(251,191,36,0.35)',
    glyph: '♪',
    tags: ['trumpet', 'brass', 'instrument'],
    recommendedFor: ['jazz', 'orchestral'],
    speed: 'slow',
    quality: 70,
  },
  {
    id: 'inst_brass',
    engine: 'instrument',
    category: 'multistem',
    name: 'Brass Section',
    tagline: 'MVSEP brass model',
    filename: '17_HP-Wind_Inst-UVR.pth',
    description: 'Brass section isolation — trumpet, trombone, horn ensemble.',
    stems: [2],
    tier: 'B',
    accent: '#f59e0b',
    glow: 'rgba(245,158,11,0.35)',
    glyph: '♪',
    tags: ['brass', 'instrument'],
    recommendedFor: ['orchestral', 'jazz'],
    speed: 'slow',
    quality: 68,
  },
  {
    id: 'inst_flute',
    engine: 'instrument',
    category: 'multistem',
    name: 'Flute',
    tagline: 'MVSEP flute model',
    filename: '17_HP-Wind_Inst-UVR.pth',
    description: 'Flute and piccolo isolation from orchestral and pop mixes.',
    stems: [2],
    tier: 'B',
    accent: '#67e8f9',
    glow: 'rgba(103,232,249,0.35)',
    glyph: '♪',
    tags: ['flute', 'woodwind', 'instrument'],
    recommendedFor: ['orchestral', 'film'],
    speed: 'slow',
    quality: 66,
  },
  {
    id: 'inst_organ',
    engine: 'instrument',
    category: 'multistem',
    name: 'Organ',
    tagline: 'BS-Roformer organ — SDR 5.08',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Pipe and Hammond organ isolation. Piano-stem proxy locally; MVSEP organ BS-Roformer on cloud.',
    stems: [2],
    tier: 'B',
    accent: '#a855f7',
    glow: 'rgba(168,85,247,0.35)',
    glyph: '♯',
    tags: ['organ', 'instrument'],
    recommendedFor: ['gospel', 'rock'],
    speed: 'slow',
    quality: 62,
  },
  {
    id: 'inst_synth',
    engine: 'instrument',
    category: 'multistem',
    name: 'Synth',
    tagline: 'MVSEP synth model',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Synthesizer and pad isolation from electronic productions.',
    stems: [2],
    tier: 'B',
    accent: '#22d3ee',
    glow: 'rgba(34,211,238,0.35)',
    glyph: '◈',
    tags: ['synth', 'instrument'],
    recommendedFor: ['electronic', 'sampling'],
    speed: 'slow',
    quality: 70,
  },
  {
    id: 'inst_percussion',
    engine: 'instrument',
    category: 'drums',
    name: 'Percussion',
    tagline: 'MVSEP percussion model',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Auxiliary percussion — shakers, congas, tambourine. Distinct from full drumsep kit.',
    stems: [2],
    tier: 'B',
    accent: '#fde047',
    glow: 'rgba(253,224,71,0.35)',
    glyph: '◎',
    tags: ['percussion', 'instrument'],
    recommendedFor: ['world', 'latin'],
    speed: 'slow',
    quality: 72,
  },
  {
    id: 'inst_harp',
    engine: 'instrument',
    category: 'multistem',
    name: 'Harp',
    tagline: 'MVSEP harp model',
    filename: 'BS-Roformer-SW.ckpt',
    description: 'Concert and Celtic harp isolation from orchestral and folk mixes.',
    stems: [2],
    tier: 'B',
    accent: '#86efac',
    glow: 'rgba(134,239,172,0.35)',
    glyph: '♪',
    tags: ['harp', 'instrument'],
    recommendedFor: ['orchestral', 'folk'],
    speed: 'slow',
    quality: 64,
  },
  {
    id: 'inst_choir',
    engine: 'instrument',
    category: 'vocal',
    name: 'Choir (Male/Female)',
    tagline: 'BS-Roformer chorus — SDR 24.1',
    filename: 'model_chorus_bs_roformer_ep_267_sdr_24.1275.ckpt',
    description: 'Split choir into male and female stems. SATB model available on MVSEP cloud.',
    stems: [2],
    tier: 'A',
    accent: '#fda4af',
    glow: 'rgba(253,164,175,0.35)',
    glyph: '♫',
    tags: ['choir', 'instrument'],
    recommendedFor: ['gospel', 'film'],
    speed: 'slow',
    quality: 86,
  },
  {
    id: 'inst_banjo',
    engine: 'instrument',
    category: 'multistem',
    name: 'Banjo',
    tagline: 'MVSEP banjo model',
    filename: 'melband_roformer_guitar_becruily.ckpt',
    description: 'Banjo plucked-string isolation. Guitar-model proxy; MVSEP banjo BS-Roformer on cloud.',
    stems: [2],
    tier: 'B',
    accent: '#eab308',
    glow: 'rgba(234,179,8,0.35)',
    glyph: '⚡',
    tags: ['banjo', 'instrument'],
    recommendedFor: ['folk', 'bluegrass'],
    speed: 'slow',
    quality: 68,
  },
  {
    id: 'inst_mandolin',
    engine: 'instrument',
    category: 'multistem',
    name: 'Mandolin',
    tagline: 'MVSEP mandolin model',
    filename: 'melband_roformer_guitar_becruily.ckpt',
    description: 'Mandolin and plucked string isolation from folk and bluegrass mixes.',
    stems: [2],
    tier: 'B',
    accent: '#ca8a04',
    glow: 'rgba(202,138,4,0.35)',
    glyph: '⚡',
    tags: ['mandolin', 'instrument'],
    recommendedFor: ['folk'],
    speed: 'slow',
    quality: 66,
  },
  {
    id: 'inst_ukulele',
    engine: 'instrument',
    category: 'multistem',
    name: 'Ukulele',
    tagline: 'MVSEP ukulele model',
    filename: 'melband_roformer_guitar_becruily.ckpt',
    description: 'Ukulele isolation from pop and indie productions.',
    stems: [2],
    tier: 'B',
    accent: '#facc15',
    glow: 'rgba(250,204,21,0.35)',
    glyph: '⚡',
    tags: ['ukulele', 'instrument'],
    recommendedFor: ['indie', 'pop'],
    speed: 'slow',
    quality: 68,
  },
  {
    id: 'inst_piano_demucs',
    engine: 'instrument',
    category: 'multistem',
    name: 'Piano (Demucs 6s)',
    tagline: 'htdemucs_6s piano stem',
    filename: 'htdemucs_6s.yaml',
    description: 'Fast piano stem via Demucs 6-source model. Lower SDR than BS-Roformer SW but quick baseline.',
    stems: [2],
    tier: 'B',
    accent: '#4ade80',
    glow: 'rgba(74,222,128,0.35)',
    glyph: '♯',
    tags: ['piano', 'demucs', 'instrument'],
    recommendedFor: ['quick tests'],
    speed: 'balanced',
    quality: 58,
  },
  {
    id: 'inst_guitar_demucs',
    engine: 'instrument',
    category: 'multistem',
    name: 'Guitar (Demucs 6s)',
    tagline: 'htdemucs_6s guitar stem',
    filename: 'htdemucs_6s.yaml',
    description: 'Fast guitar stem via Demucs 6-source. Use becruily or SW models for production quality.',
    stems: [2],
    tier: 'B',
    accent: '#4ade80',
    glow: 'rgba(74,222,128,0.35)',
    glyph: '⚡',
    tags: ['guitar', 'demucs', 'instrument'],
    recommendedFor: ['quick tests'],
    speed: 'balanced',
    quality: 56,
  },
];